version: '3.9'

services:

  # ---------------------------------
  # Flask web app
  # ---------------------------------
  web:
    build: .
    #docker-compose command: python server.py
    ports:
      - "9200:5000"
    #volumes:
    #  - /:/
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"