version: '3.9'

services:

  # ---------------------------------
  # Flask web app
  # ---------------------------------
  web:
    build: .
    command: python server.py
    ports:
      - "8000:5000"
    #volumes:
    #  - ./:./
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"