# IRIS dataset
# If any datetime it should be called date

pid: None


filepath: ./datasets/iris/data.csv
output: ./outputs/iris/

features:
  - sepal length (cm)
  - sepal width (cm)
  - petal length (cm)
  - petal width (cm)

estimators:
  - sae
  - pca
  - pcak
  - pcai
  - icaf
  - iso
  - lda

params:
  pca:
    pca__n_components: [2]

  pcak:
    pcak__n_components: [2]

  pcai:
    pcai__n_components: [2]

  nmf:
    nmf__n_components: [2]
    nmf__tol: [0.0001, 0.001, 0.01]

  icaf:
    icaf__n_components: [2]

  iso:
    iso__n_components: [2]
    iso__n_neighbors: [5, 10]

  lda:
    lda__n_components: [2]
    lda__max_iter: [5]
    lda__learning_method: [online]
    lda__learning_offset: [50]
    lda__random_state: [0]

  sae:
    sae__module__layers:
      - [4, 2]
      - [4, 3, 2]
    sae__lr: [0.01]
    sae__max_epochs: [10]