# Configuration for Dengue.
#
# .. note: At the moment, the column with dates should be
#          called dates and ignores completely the time
#          information.

# The column that identifies the patient. If not
# specified or set to None, the index will be used
# as identifier.
pid: study_no

# Location of the data.
filepath: ./datasets/dengue/data.csv

# Path to store the models.
output: ./outputs/dengue/

# Features to be used for training. The features will
# be automatically sorted alphabetically. Thus, the
# order does not matter.
features:
  - age
  - weight
  - plt
  - haematocrit_percent
  - body_temperature

# Columns that will be considered as targets. These are
# used to compute metrics such as the GMM (Gaussian
# Mixture Models).
targets:
  - severe
  - warning
  - mild
  - vomiting
  - bleeding
  - bleeding_mucosal
  - bleeding_skin
  - bleeding_gum
  - bleeding_gi
  - ascites
  - abdominal_pain
  - abdominal_tenderness
  - shock
  - severe_leak
  - severe_bleed
  - severe_organ

# The models to use. For information about the models that
# ara available (or to include more) please see the variable
# DEFAULT_ESTIMATORS within the file ls2d.settings.py.
estimators:
  - sae
  #- pca

# The parameters to create the ParameterGrid to create and
# evaluate different hyperparameter configurations. Please
# ensure that the hyperparameters ae specified, otherwise
# a default empty dictionary will be returned.
params:
  pca:
    pca__n_components: [2]

  sae:
    # Remember that the first layer should be equal to the
    # number of inputs and the last layer should be two so
    # that the embeddings can be displayed in the 2D space.
    sae__module__layers:
      - [5, 2]
      - [5, 3, 2]
    sae__lr: [0.001, 0.00001]
    #sae__batch_size: [16, 32]
    sae__max_epochs: [10, 500]



# -------------------------
# Configuring the interface
# -------------------------
#
outcomes:
  - severe
  - warning
  - mild
  - vomiting
  - bleeding
  - bleeding_mucosal
  - bleeding_skin
  - bleeding_gum
  - bleeding_gi
  - ascites
  - abdominal_pain
  - abdominal_tenderness
  - shock
  - gender
  - severe_leak
  - severe_bleed
  - severe_organ
  - date
  - dsource
  - pcr_dengue_serotype

#
drop: []

#
#mappings:
  #gender:
  #  Female: 0
  #  Male: 1

# if no aggregation specified then the
# agg function 'max' or 'first' will be
# used. Only useful when pid is not null.
aggregations:
  dsource: last
  age: max
  weight: mean
  plt: min
  haematocrit_percent: max
  body_temperature: max
  gender: first
  date: last
  shock: max
  study_no: first

#
titles:
  plt: PLT
  haematocrit_percent: HCT
  body_temperature: Temperature

#
order:
  study_no: 0
  distance: 1
  age: 3
  weight: 4
  plt: 5
  haematocrit_percent: 6
  body_temperature: 7
  shock: 8
